### ISSUE TITLE
Using alamofire i'm downloading pdf file and save on destination path.  Its working fine till ios 10 but ios 11 its not working.

### ISSUE THREAD

**Issue by souravgarg12** [Alamofire/Alamofire#2319]
please check following code.

```swift
let fileManager = FileManager()

let pathComponent = "dp"+String(self.dPackageId)+".pdf"
let directoryURL: URL = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask)[0]
let folderPath: URL = directoryURL.appendingPathComponent("Downloads", isDirectory: true)
let fileURL: URL = folderPath.appendingPathComponent(pathComponent)
self.destinationURLForFile = fileURL

let destination: DownloadRequest.DownloadFileDestination = { _, _ in
    return (fileURL, [.removePreviousFile, .createIntermediateDirectories])
}
let parameters: Parameters = ["foo": "bar"]

Alamofire.download(dpUrl!, method: .get, parameters: parameters, encoding: JSONEncoding.default, to: destination)
    .downloadProgress(queue: DispatchQueue.global(qos: .utility)) { progress in
        print("Progress: \(progress.fractionCompleted)")
    }
    .responseJSON { response in
        if let statusCode = response.response?.statusCode, statusCode == 200 {
            let pdfUrl = URL(fileURLWithPath: self.destinationURLForFile.path)
            let requestObj = NSURLRequest(url: pdfUrl as URL)
            self.webPreview?.loadRequest(requestObj as URLRequest)
        }
        return
    }
```

getting error in ios 11 

Task <B2D89618-99AA-4FAA-8921-13243B3D63EC>.<5089> finished with error - code: -1001
] 

NSURLConnection finished with error - code -1100

FAILURE: Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={_kCFStreamErrorCodeKey=-2102, NSURLSessionDownloadTaskResumeData=<CFData 0x600000456d40 [0x10a67c9b0]>{length = 6151, capacity = 16384, bytes = 0x3c3f786d6c2076657273696f6e3d2231 ... 2f706c6973743e0a}, NSUnderlyingError=0x600000647ce0 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "(null)" UserInfo={_kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4}}, NSLocalizedDescription=The request timed out., NSErrorFailingURLStringKey=http://www.pdf995.com/samples/pdf.pdf, NSErrorFailingURLKey=http://www.pdf995.com/samples/pdf.pdf, _kCFStreamErrorDomainKey=4}
[Timeline]: Timeline: { "Request Start Time": 529337121.774, "Initial Response Time": 529337122.625, "Request Completed Time": 529337184.963, "Serialization Completed Time": 529337184.963, "Latency": 0.852 secs, "Request Duration": 63.189 secs, "Serialization Duration": 0.000 secs, "Total Duration": 63.189 secs }
Optional(Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={_kCFStreamErrorCodeKey=-2102, NSURLSessionDownloadTaskResumeData=<CFData 0x600000456d40 [0x10a67c9b0]>{length = 6151, capacity = 16384, bytes = 0x3c3f786d6c2076657273696f6e3d2231 ... 2f706c6973743e0a}, NSUnderlyingError=0x600000647ce0 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "(null)" UserInfo={_kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4}}, NSLocalizedDescription=The request timed out., NSErrorFailingURLStringKey=http://www.pdf995.com/samples/pdf.pdf, NSErrorFailingURLKey=http://www.pdf995.com/samples/pdf.pdf, _kCFStreamErrorDomainKey=4})

**Comment by johnnynanjiang** [comment]
I can't reproduce the issue on iOS 11, you could try running the following unit test. I ran it and it successfully downloaded the PDF mentioned in your comment.

    func testDownloadPDFfile() {
        // Given
        let fileURL = testDirectoryURL.appendingPathComponent("test.pdf")
        let expectation = self.expectation(description: "Download PDF files should work")
        var response: DefaultDownloadResponse?
        
        // When
        Alamofire.download("http://www.pdf995.com/samples/pdf.pdf", to: { _, _ in (fileURL, [])})
            .response { res in
                response = res
                expectation.fulfill()
        }
        
        waitForExpectations(timeout: timeout, handler: nil)
        
        // Then
        XCTAssertEqual(response?.response?.statusCode, 200)
    }

**Comment by jshier** [comment]
@souravgarg12 The error clearly states your request timed out, as it took over 60 seconds. While many things can cause that error, Alamofire isn't one of them.

**Comment by nmdias** [comment]
@souravgarg12 were you able to find a solution to this?

I have, what I think is the same issue. The request weirdly shows has a timeout. But the file is actually downloaded successfully. I can see it in the Web Proxy, as well as in the tmp containers folder as a temporary file:

CFNetworkDownload_DABBwL.tmp

If I rename it to end in pdf, it shows the full pdf successfully downloaded.

Even the `downloadProgress`shows the file being downloaded very quickly, then it just hangs there until it times out..

**Comment by nmdias** [comment]
Fixed my issue:

In iOS 10 this doesn't happen, by the way. 

In my case, I was encoding JSON parameters in the GET request:

```swift
case .documentDownload(let uniqueID):
    return try! JSONEncoding.default.encode(urlRequest, with: ["UniqueID": uniqueID])
```

After removing them, the response completion handler started to successfully being called.  If for some reason I encode JSON parameters in the GET request when downloading the file, the file does get downloaded to the temp folder, but after that, hangs until it times out.

**Comment by ali6p** [comment]
I don't know why, but use  
```swift
let requestObj = NSURLRequest(url: self.destinationURLForFile)
```
instead of 
```swift
let pdfUrl = URL(fileURLWithPath: self.destinationURLForFile.path) 
let requestObj = NSURLRequest(url: pdfUrl as URL)
```
Both of them work in the simulator, but only first one works on real device (directly created request with URL).

**Comment by souravgarg12** [comment]
Thanks for your reply...
I m still facing same issue. I have try all way which you have described.
can any body tell how i can increase request timeout time?

Thanks in advance

**Comment by aneeskodappana** [comment]
@souravgarg12 have u fixed the issue ?
