### ISSUE TITLE
When starting the app in airplane mode, the listener is not notified

### ISSUE THREAD

**Issue by alekop** [Alamofire/Alamofire#2677]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

```
let reachability = ReachabilityNetworkManager(host: "www.apple.com")!
reachability.listener = { state in
    print("isReachable: \(state)")
}
reachability.startListening()
```

## What did you expect to happen?

The `print` statement should have printed "isReachable: false"

## What happened instead?

Nothing is printed when starting with no connectivity. But if you start the app with connectivity, it will print. The initial notification is not called in airplane mode.

The issue is that `flags` and `previousFlags` both have a rawValue of 0, so the guard in notifyListener returns. The previous flags should probably default unknown, rather than 0, which means not-reachable.

## Alamofire Environment

**Alamofire version: 4.8.0**
**Xcode version: 10.1**
**Swift version: 4.2**
**Platform(s) running Alamofire: iOS**
**macOS version running Xcode: 10.13.6**

**Comment by cnoon** [comment]
Hi @alekop,

Thank you for the report. Could you report which device and version of iOS you are running? Also, could you try the following code and see if it behaves better?

```swift
let reachability = ReachabilityNetworkManager()!
reachability.listener = { print("isReachable: \($0)") }
reachability.startListening()
```

> I tend to use the non-host specific initializer as the `host` version tends to be less reliable.

If you could report back on your findings I'd greatly appreciate it.

**Comment by alekop** [comment]
Hi @cnoon,

I tried the no-hostname initializer, but it didn't make any difference. The issue seems to be here, in NetworkReachabilityManager.swift:

```
    listenerQueue.async {
        self.previousFlags = SCNetworkReachabilityFlags()
        self.notifyListener(self.flags ?? SCNetworkReachabilityFlags())
    }
```

Both `previousFlags`, and `flags` get initialized to the same value, which trips the guard in `notifyListener`:

```
    func notifyListener(_ flags: SCNetworkReachabilityFlags) {
        guard previousFlags != flags else { return }
        previousFlags = flags
        
        listener?(networkReachabilityStatusForFlags(flags))
    }
```

**Comment by cnoon** [comment]
What versions of iOS have you tried this on @alekop? I'm guessing this is a change in functionality somewhere along the line.

**Comment by alekop** [comment]
I tried 11.4.1, 12, 12.1.

**Comment by cnoon** [comment]
Cool. Thank you for all the info here!

My guess for now is that the behavior here changed somewhere along the lines under-the-hood because I'm positive this used to work on older versions. I'll do some investigation and get a fix put together. Just FYI, I'll be out on PTO for the rest of the week so I really doubt I'll be able to get a patch put together until I get back. If this is super pressing, I'd suggest making the fix you suggested and give it a whirl in a fork. If you're confident in the change, I'd also recommend putting together a PR.

> The biggest thing we'll need to investigate with making that change is that it is compatible with older versions of iOS.

**Comment by cnoon** [comment]
Okay @alekop, I just pushed up #2688 to resolve the issue you are seeing. Your breakdown of the issue was spot on and I modified the original value of `previousFlags` accordingly. There's a bunch more detail in #2688 specifically.

I'm going to go ahead and close this issue out. Let's continue this conversation in #2688.

Cheers. 🍻

**Comment by agnosticdev** [comment]
> My guess for now is that the behavior here changed somewhere along the lines under-the-hood because I'm positive this used to work on older versions. 

I'm positive this used to work.  Thank you for reporting this @alekop.
I need to do some regression testing on my own projects.

**Comment by SparklingAir** [comment]
Hello! Problem is still here. I run my app from Xcode via wire on the device with turned on airplane mode and NetworkReachabilityManager()?.isReachable returns "reachable" merely once.
- Alamofire 5.6.1
- Xcode 13.2.1
- Swift 5
- iPhone 12
- iOS 15.5
