### ISSUE TITLE
WATCHOS_DEPLOYMENT_TARGET less than 6.0 is not compiled if Alamofire is installed via Swift Packages

### ISSUE THREAD

**Issue by maxx-cyber** [Alamofire/Alamofire#3258]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

1. Create new project iOS App with Watch App (WATCHOS_DEPLOYMENT_TARGET is 6.2 by default)
2. Integrate Alamofire to WatchKit Extension via Swift Packages (it was built successfully)
3. Set WATCHOS_DEPLOYMENT_TARGET for example to 5.0

## What did you expect to happen?

I expect that it should be built successfully as declared watchOS 3.0+

## What happened instead?

Linker error: 
Undefined symbol: _OBJC_CLASS_$_NSURLSessionTaskMetrics

## Alamofire Environment

**Alamofire version: 5.2.1**
**Xcode version: 11.5**
**Swift version: 5.1**
**Platform(s) running Alamofire: watchOS**
**macOS version running Xcode: 10.15.5**

## Demo Project

[TestAlamofire.zip](https://github.com/Alamofire/Alamofire/files/4927751/TestAlamofire.zip)

**Comment by jshier** [comment]
Hmm, some Apple platforms do require CFNetwork to be linked in order to properly find some symbols. For now you should try adding an explicit linking of CFNetwork to your project and I'll see how we can replicate that using SPM.

**Comment by jshier** [comment]
@maxx-cyber Yes, looks like adding an explicit linker statement fixes the issue. You can try the `bug/spm-explicit-cfnetwork-linking` branch for now until I get a PR up and merged.

**Comment by jshier** [comment]
This fix was released as part of Alamofire 5.2.2.

**Comment by maxx-cyber** [comment]
Hi @jshier 
This issue is still reproduced under Xcode 12 beta 2 even after fix :)

**Comment by jshier** [comment]
@maxx-cyber Bizarrely, the issue still exists even after updating the package in Xcode to 5.2.2. However, removing and adding the package again *at the exact same version* works fine. I'll report it as an SPM in Xcode bug.

**Comment by maxx-cyber** [comment]
@jshier Updating package to 5.2.2 under Xcode 11.6 works fine for me without removing and adding the package. But under Xcode 12 beta 2 it doesn't work at all, even after removing and adding the package, even after removing DerivedData folder.

**Comment by maxx-cyber** [comment]
@jshier Just try it

**Comment by jshier** [comment]
Your sample project works fine for me after removing and adding the package in Xcode 12b2. This seems to be a bug in SPM, which I've filed as FB8080727.

**Comment by maxx-cyber** [comment]
I've removed ~/Library/Develop folder, reboot mac, created absolutely new sample project under Xcode 12b2, decreased watchOS deployment target to 5.0 (it requires to comment some code to be compilable), added Alamofire swift package and all this doesn't help. I have macOS 10.15.5, did you update it to 10.15.6?

**Comment by jshier** [comment]
I am on 10.15.6, but it's unlikely that makes a difference here, since Xcode's SPM functionality is self contained. I've confirmed again that removing Alamofire and adding again lets the build work.

**Comment by jshier** [comment]
Actually, it looks like adding the framework again doesn't add it to any targets, but the build still works. Adding it to the watch extension does break the build in general. You can manually work around the linking error by adding `-framework CFNetwork` to the "Other Linker Flags" setting on your extension target.

**Comment by maxx-cyber** [comment]
Yes, `-framework CFNetwork` works 👍
May be it will be nice to add this to installation instruction.

**Comment by jshier** [comment]
It's only necessary due to Xcode 12 ignoring the setting from the package. Hopefully they just fix the bug.
