### ISSUE TITLE
Xcode 13 betas: Build fails in Combine

### ISSUE THREAD

**Issue by phiren** [Alamofire/Alamofire#3481]
Facing below error:
SourcePackages/checkouts/Alamofire/Source/Combine.swift:25:5: Failed to build module 'Combine'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.5 (swiftlang-1300.0.24.14 clang-1300.0.25.10)', while this compiler is 'Apple Swift version 5.5 (swiftlang-1300.0.24.13 clang-1300.0.25.10)'). Please select a toolchain which matches the SDK.

## What did you expect to happen?

it should build project successfully.

## What happened instead?

Its throwing error. Same problem was in Kingfisher GitHub repository, They created new branch with fix, changed deployment target from v10 to 12

## Alamofire Environment

**Alamofire Version:** 5.2.1
**Dependency Manager:** Swift Package Manager
**Xcode Version:** Version 13.0 beta 3 (13A5192i)
**Swift Version:** Swift 5
**Platform(s) Running Alamofire:** iOS
**macOS Version Running Xcode:** 12.0 Beta (21A5284e)

**Comment by jshier** [comment]
Yeah, looks like they broken Combine compilation in beta 3. You'll need to go back to beta 2 or wait for the next beta.

**Comment by jeremyfalldev** [comment]
Don't we have a temporary solution?

**Comment by jshier** [comment]
@jeremyfalldev Only solution is to remove all use of Combine until they fix the issue. I don't think that's worth a branch that will (hopefully) only live a week, but anyone who really needs it can remove the `Combine.swift` file which should prevent the linking of Combine. If the issue continues we could create a longer running fix branch.

**Comment by jeremyfalldev** [comment]
@jshier Thank you for the quick response. I thought there is an easy & quick solution that is similar to what Kingfisher did.
Comments from @phiren:
> Same problem was in Kingfisher GitHub repository, They created new branch with fix, changed deployment target from v10 to 12

**Comment by jeremyfalldev** [comment]
@jshier Any idea?

**Comment by castor55** [comment]
Same issue here. I use SPM and get an error while archiving a new build.
Any solution?

**Comment by zhangqifan** [comment]
Beta: Xcode 13 Beta 4

I am using CocoaPods and switch the version back to 5.1.0(without Combine). It works for me. Still waiting for the solution, maybe on beta 5?

**Comment by jshier** [comment]
I can't believe this is still broken. I'll see if I can get a branch up over the next few days.

**Comment by lucasfischer** [comment]
Xcode 13 beta 4 fixed this for me. Seems to be resolved. Using SwiftPM and Alamofire 5.4.3.

**Comment by phiren** [comment]
It still not working in beta 4

**Comment by paulmesa-paypal** [comment]
Does anyone know of a feedback report or radar on apples side tracking this?

**Comment by jshier** [comment]
@phiren This works for me using SPM as well run Xcode 13b4 (13A5201i).

**Comment by phiren** [comment]
@jshier, Problem exist with following configuration for me. Not sure because of any Xcode setting causing that. 
Project Deployment Target: iOS 12.2

**Comment by sammcewan** [comment]
Discussion in here folks:
https://developer.apple.com/forums/thread/682285

**Comment by jshier** [comment]
This seems to only be broken when building in Release mode for a device. Building in debug or on the simulator seems to work fine. You can use the `feature/async-handlers` branch for now to get a version without Combine support.

**Comment by ast3150** [comment]
For us this is also broken when building a test target to be run on the simulator. Using Xcode 13 b4.

**Comment by jshier** [comment]
Yep, this is still broken. You can continue using the branch or update your deployment target to iOS 12+ (and make sure your dependencies have that deployment target) to fix it.

**Comment by teeeeeegz** [comment]
> Yep, this is still broken. You can continue using the branch or update your deployment target to iOS 12+ (and make sure your dependencies have that deployment target) to fix it.

Just a quick ELI 5 for other noobies like me that just figured out how add Alamofire as a local package (and need to retain Combine support);
1. Clone the Alamofire repo locally to a folder
2. Xcode > File > Add Packages > Add Local > select the cloned Alamofire repo
3. Open Package.swift, and update the platforms to `[.macOS(.v10_15), .iOS(.v13), .tvOS(.v13), .watchOS(.v6)]`
4. Archive your iOS app ✅

I didn't remove Alamofire as a Package Dependency before I did this, as per this [Apple doc](https://developer.apple.com/documentation/swift_packages/editing_a_package_dependency_as_a_local_package).

Happy archiving!

**Comment by jshier** [comment]
@teeeeeegz I've now opened the `workaround/xcode13` branch, please give it a try, as it should have the updated deployment targets.

**Comment by teeeeeegz** [comment]
> @teeeeeegz I've now opened the `workaround/xcode13` branch, please give it a try, as it should have the updated deployment targets.

Seems to have worked a treat. Thank you 🙂

**Comment by jefernandez** [comment]
it doesn't work to me when I run in simulator

**Comment by mzygar** [comment]
If anyone is facing the issue in a project that uses CocoaPods, there is a workaround that does not require checking out the special branch. You can adjust the deployment  target of pods manually in a Podfile:
```
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 12.0
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
            end
        end
    end
end
```

**Comment by kapfab** [comment]
No new Xcode beta for almost one month now, and latest beta 5 did not fix this issue.
It’s starting to be a bit worrying (not only for Alamofire but for all apps & frameworks struggling to support iOS < 12).
What about fixing the issue the way Realm did? (https://github.com/realm/realm-cocoa/pull/7401)

**Comment by Olaf2018** [comment]
It still not working in beta 5

**Comment by marciogranzotto** [comment]
Apple's new iPhones event is on Sep. 14th, and last year they announced that iOS 14 would be released one day later. I think we are running out of time to fix this.

**Comment by jshier** [comment]
Interesting. I've updated the `xcode13` branch with the 32-bit avoiding approach Realm used. Please try it out. If it works I'm comfortable shipping it so I can ship a 5.4.4 release right after.

**Comment by jlcvp** [comment]
> Interesting. I've updated the `xcode13` branch with the 32-bit avoiding approach Realm used. Please try it out. If it works I'm comfortable shipping it so I can ship a 5.4.4 release right after.

I'm getting a new error in the pre-processor `#if` in the Combine.swift file you've changed with the Realm approach. As follows:
```
Failed to build module 'Combine'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.5 (swiftlang-1300.0.29.1 clang-1300.0.28.1)', while this compiler is 'Apple Swift version 5.5 (swiftlang-1300.0.29.102 clang-1300.0.28.1)'). Please select a toolchain which matches the SDK.
```
<img width="1057" alt="image" src="https://user-images.githubusercontent.com/2317417/132567058-a079a206-4638-45b5-b428-ede74cbe6a8c.png">

Removing the `canImport(Combine)` part seems to resolve it and the code run just fine. Maybe this is the reason Realm folks removed it from theirs too.

**Comment by jshier** [comment]
@jlcvp Ah yes, `canImport` works by trying to link the framework. I've removed the check. Since Combine is unconditionally available in Xcode 11+, and we'll likely move to requiring Xcode 12 soon, this should still be shippable. I've fixed it, give it another shot.

**Comment by freak4pc** [comment]
I'm still getting a lot of build error even when using the `xcode13` branch. Am I doing anything funky I'm not aware of ? 

<img width="830" alt="image" src="https://user-images.githubusercontent.com/605076/132581338-316f90bb-b855-4caf-a61f-0875c675361a.png">

**Comment by jlcvp** [comment]
@jshier working good now, thanks

**Comment by funkenstrahlen** [comment]
I can confirm building Alamofire with Version 13.0 beta 5 (13A5212g) works when using the `xcode13` branch of this project.

**Comment by pvroosendaal** [comment]
Solution seems to work now indeed, thanks! @jshier, I'm pointing to the `master` branch now. When do you expect to ship 5.4.4?

**Comment by freak4pc** [comment]
@jshier This seems to be fixed on Xcode 13 RC1! Hallelujah!

**Comment by jshier** [comment]
@jlcvp Can you confirm that 5.4.3 works in the Xcode 13 RC as well? If it does I may just keep the change but roll it into 5.5 instead.

**Comment by jshier** [comment]
I have noticed that, no matter how I check for Combine, it fails to run tests on older simulators because it tries to weak load a Combine symbol:

```
dyld: lazy symbol binding failed: can't resolve symbol _$s7Combine14AnyCancellableCMa in /Users/jshier/Library/Developer/Xcode/DerivedData/Alamofire-gqexvpxfnitcltctvgfmsnsdspgw/Build/Products/Debug-iphonesimulator/Alamofire iOS Tests.xctest/Alamofire iOS Tests because dependent dylib #7 could not be loaded
dyld: can't resolve symbol _$s7Combine14AnyCancellableCMa in /Users/jshier/Library/Developer/Xcode/DerivedData/Alamofire-gqexvpxfnitcltctvgfmsnsdspgw/Build/Products/Debug-iphonesimulator/Alamofire iOS Tests.xctest/Alamofire iOS Tests because dependent dylib #7 could not be loaded
CoreSimulator 776.3 - Device: iPhone 8 (45622991-79AE-4C14-8FA0-DE97AA94C525) - Runtime: iOS 11.4 (15F79) - DeviceType: iPhone 8
```

Can anyone confirm whether this would be an issue on older devices, or is it just the sim?

**Comment by pvroosendaal** [comment]
I can confirm it works with Xcode RC as well!

**Comment by jshier** [comment]
Thanks! Sounds like we don't need a 5.4.4 release after all. I'll shift focus to 5.5 and production concurrency support. Thanks everyone!

**Comment by jlcvp** [comment]
@jshier 5.4.3 working fine in Xcode 13 RC

**Comment by bradmartin** [comment]
Hate to chime on a closed issue. Updated XCode today `Version 13.0 (13A233)` to work on WatchOS8 and the project fails with the same errors mentioned in this issue.

Currently using `pod 'Alamofire', '~> 5.4.3'`

<img width="1458" alt="ksks" src="https://user-images.githubusercontent.com/6006148/134087775-36f4aaea-1e76-45f3-ac2d-09f1da6376cf.png">

Looks like last reports were `5.4.3` worked in the XCode 13RC. Did anyone happen to be building for WatchOS?

**Comment by jshier** [comment]
Thanks. I'll do a quick 5.4.4.

**Comment by bradmartin** [comment]
@jshier - you prefer I open a new issue for the following?

Bumped to `5.4.4` : `pod 'Alamofire', '~> 5.4.4'`

<img width="1196" alt="asdf" src="https://user-images.githubusercontent.com/6006148/134097731-4fda8a90-c75e-48c5-bfcf-15898c6c0ad2.png">

I've also deleted `DerivedData`, restarted the Mac to ensure the XCode update wasn't still hanging somewhere, clean build and no luck.

Happy to help try some things on my end with some assistance if possible. Thanks again for the help 👍🏻 .

**Comment by jshier** [comment]
Yes, as it doesn't seem to have anything to do with the Combine build failure. I'd also like a more detailed build log, not just a screenshot. The project builds just fine in the watch simulator locally, so I'm not sure what your difference might be.

**Comment by JakubTHOC** [comment]
Ok, I have the same issue with Xcode Version 13.0 (13A233)
`
CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler (in target 'Alamofire' from project 'Pods')
    cd /Users/user/Sources/project/Dependencies/Pods
    export DEVELOPER_DIR\=/Applications/Xcode.app/Contents/Developer
    export SDKROOT\=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.0.sdk
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc -incremental -module-name Alamofire -Onone -enable-batch-mode -enforce-exclusivity\=checked @/Users/user/Library/Developer/Xcode/DerivedData/RNS-bsgnunpwazmjijafihbjsowwtfxs/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/Alamofire.build/Objects-normal/arm64/Alamofire.SwiftFileList -DDEBUG -D COCOAPODS -suppress-warnings -sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.0.sdk -target arm64-apple-ios12.0 -g -module-cache-path /Users/user/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -Xfrontend -serialize-debugging-options -embed-bitcode-marker -enable-testing -index-store-path /Users/user/Library/Developer/Xcode/DerivedData/RNS-bsgnunpwazmjijafihbjsowwtfxs/Index/DataStore -swift-version 5 -I /Users/user/Library/Developer/Xcode/DerivedData/RNS-bsgnunpwazmjijafihbjsowwtfxs/Build/Products/Debug-iphoneos/Alamofire -F /Users/user/Library/Developer/Xcode/DerivedData/RNS-bsgnunpwazmjijafihbjsowwtfxs/Build/Products/Debug-iphoneos/Alamofire -c -j12 -output-file-map /Users/user/Library/Developer/Xcode/DerivedData/RNS-bsgnunpwazmjijafihbjsowwtfxs/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/Alamofire.build/Objects-normal/arm64/Alamofire-OutputFileMap.json -parseable-output -serialize-diagnostics -emit-dependencies -emit-module -emit-module-path /Users/user/Library/Developer/Xcode/DerivedData/RNS-bsgnunpwazmjijafihbjsowwtfxs/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/Alamofire.build/Objects-normal/arm64/Alamofire.swiftmodule -Xcc -I/Users/user/Library/Developer/Xcode/DerivedData/RNS-bsgnunpwazmjijafihbjsowwtfxs/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/Alamofire.build/swift-overrides.hmap -Xcc -iquote -Xcc /Users/user/Library/Developer/Xcode/DerivedData/RNS-bsgnunpwazmjijafihbjsowwtfxs/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/Alamofire.build/Alamofire-generated-files.hmap -Xcc -I/Users/user/Library/Developer/Xcode/DerivedData/RNS-bsgnunpwazmjijafihbjsowwtfxs/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/Alamofire.build/Alamofire-own-target-headers.hmap -Xcc -I/Users/user/Library/Developer/Xcode/DerivedData/RNS-bsgnunpwazmjijafihbjsowwtfxs/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/Alamofire.build/Alamofire-all-non-framework-target-headers.hmap -Xcc -ivfsoverlay -Xcc /Users/user/Library/Developer/Xcode/DerivedData/RNS-bsgnunpwazmjijafihbjsowwtfxs/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/Alamofire.build/all-product-headers.yaml -Xcc -iquote -Xcc /Users/user/Library/Developer/Xcode/DerivedData/RNS-bsgnunpwazmjijafihbjsowwtfxs/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/Alamofire.build/Alamofire-project-headers.hmap -Xcc -I/Users/user/Library/Developer/Xcode/DerivedData/RNS-bsgnunpwazmjijafihbjsowwtfxs/Build/Products/Debug-iphoneos/Alamofire/include -Xcc -I/Users/user/Library/Developer/Xcode/DerivedData/RNS-bsgnunpwazmjijafihbjsowwtfxs/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/Alamofire.build/DerivedSources-normal/arm64 -Xcc -I/Users/user/Library/Developer/Xcode/DerivedData/RNS-bsgnunpwazmjijafihbjsowwtfxs/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/Alamofire.build/DerivedSources/arm64 -Xcc -I/Users/user/Library/Developer/Xcode/DerivedData/RNS-bsgnunpwazmjijafihbjsowwtfxs/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/Alamofire.build/DerivedSources -Xcc -DPOD_CONFIGURATION_DEBUG\=1 -Xcc -DDEBUG\=1 -Xcc -DCOCOAPODS\=1 -emit-objc-header -emit-objc-header-path /Users/user/Library/Developer/Xcode/DerivedData/RNS-bsgnunpwazmjijafihbjsowwtfxs/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/Alamofire.build/Objects-normal/arm64/Alamofire-Swift.h -import-underlying-module -Xcc -ivfsoverlay -Xcc /Users/user/Library/Developer/Xcode/DerivedData/RNS-bsgnunpwazmjijafihbjsowwtfxs/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/Alamofire.build/unextended-module-overlay.yaml -working-directory /Users/user/Sources/project/Dependencies/Pods

Command CompileSwiftSources failed with a nonzero exit code
`

**Comment by jshier** [comment]
@JakubTHOC That's not the same issue. It's a compiler crash similar to #3497.

**Comment by qs991011** [comment]
In my xcode(Version 13.0 (13A233) show this errors
`
Cannot test target “Alamofire iOS Tests” on “iPhone”: Logic Testing Unavailable Logic Testing on iOS devices is not supported. You can run logic tests on the Simulator.
Domain: XCTHTestRunSpecificationErrorDomain
Code: 2
`
mac Version 11.4
