### ISSUE TITLE
qualityOfService need ios 8.0

### ISSUE THREAD

**Issue by twmsh** [Alamofire/Alamofire#472]
class TaskDelegate init 
operationQueue.qualityOfService = NSQualityOfService.Utility

NSOperationQueue.qualityOfService  need ios 8.0

**Comment by cnoon** [comment]
Thank you for bringing this issue to our attention. We'll get it fixed up right away!

**Comment by cnoon** [comment]
Fixed in 768b71e8. Thanks again for reporting this @twmsh! 🍻

**Comment by btelintelo** [comment]
It looks like this issue is back in the swift 2.0 branch Request.swift

if #available(OSX 10.10, *) {
       operationQueue.qualityOfService = NSQualityOfService.Utility
}

**Comment by cnoon** [comment]
Not sure what you're referring to @btelintelo. There is no issue that is back. That check is needed and there is no iOS check needed since we're dropping support for iOS 7 in Alamofire 2.0.

**Comment by btelintelo** [comment]
Ah ok, didn't realize support was being dropped for iOS7! This was the one thing not working for me with iOS7 and swift 2.0
