### ISSUE TITLE
[Swift 2]: Build fails during Archive in Xcode 7 Beta 2

### ISSUE THREAD

**Issue by kamoljan** [Alamofire/Alamofire#624]
Hi @cnoon 

Build fails during Archive with the following log:

    Pods.build/Release-iphoneos/Alamofire.build/Objects-normal/arm64/ServerTrustPolicy.o

     Assertion failed: (isa<X>(Val) && "cast<Ty>() argument of incompatible type!"), function cast, file /Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-700.0.47.4/src/llvm/include/llvm/Support/Casting.h, line 237.
     0  swift                    0x000000010b037b8b llvm::sys::PrintStackTrace(__sFILE*) + 43
     1  swift                    0x000000010b0382cb SignalHandler(int) + 379
     2  libsystem_platform.dylib 0x00007fff8cd85eaa _sigtramp + 26
     3  libsystem_platform.dylib 0x00007fc1f543aa30 _sigtramp + 1751862176
     4  libsystem_c.dylib        0x00007fff9553e41b abort + 129
     5  libsystem_c.dylib        0x00007fff95505a64 basename + 0
     6  swift                    0x0000000109550a10 hoistOrCopySelf(swift::ApplyInst*, swift::SILInstruction*, swift::DominanceInfo*, bool) + 624
     7  swift                    0x00000001095503ef swift::ArraySemanticsCall::hoistOrCopy(swift::SILInstruction*, swift::DominanceInfo*, bool) + 319
     8  swift                    0x00000001093a14bb (anonymous namespace)::SwiftArrayOptPass::run() + 4283
     9  swift                    0x00000001093140ae swift::SILPassManager::runFunctionPasses(llvm::ArrayRef<swift::SILFunctionTransform*>) + 1598
     10 swift                    0x0000000109314d28 swift::SILPassManager::runOneIteration() + 984
     11 swift                    0x0000000109311cd4 swift::runSILOptimizationPasses(swift::SILModule&) + 500
     12 swift                    0x000000010901de08 performCompile(swift::CompilerInstance&, swift::CompilerInvocation&, llvm::ArrayRef<char const*>, int&) + 9992
     13 swift                    0x000000010901b4e3 frontend_main(llvm::ArrayRef<char const*>, char const*, void*) + 2627
     14 swift                    0x00000001090175af main + 2015
     15 libdyld.dylib            0x00007fff8cadf5ad start + 1
     Stack dump:
      ...
     -o /Users/kamol/Library/Developer/Xcode/DerivedData/ShoppingXXX-dlpuiajnjtnnesfkfvqddrrirgnd/Build/Intermediates/ArchiveIntermediates/ShoppingXXX/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/Alamofire.build/Objects-normal/arm64/ServerTrustPolicy.o 
     1.	While running SILFunctionTransform "SIL Swift Array Optimization" on SILFunction "@_TFO9Alamofire17ServerTrustPolicy19evaluateServerTrustfS0_FTCSo8SecTrust14isValidForHostSS_Sb".

My Podfile:

       pod 'Alamofire', :git => 'git@github.com:Alamofire/Alamofire.git', :tag => 'swift-2.0'

**Comment by cnoon** [comment]
Yep, you'll need to update to Xcode 7 beta 4 to use the latest commits in the `swift-2.0` branch.

**Comment by kamoljan** [comment]
@cnoon sorry, it was type. I am on Xcode 7 Beta 4.

**Comment by cnoon** [comment]
Try to run `pod update` again. I pushed a fix for this problem yesterday in fb8c54c86944516d0b838a33205d3a8e9809e539 that you may not have picked up.

**Comment by kamoljan** [comment]
@cnoon all good, thank you!

**Comment by codeOfRobin** [comment]
Still get multiple errors. Is this because I'm on El Capitan?

![screen shot 2015-07-29 at 11 47 59 pm](https://cloud.githubusercontent.com/assets/5009041/8965975/50ea1bd6-364c-11e5-8517-7e08314702e7.png)

**Comment by bruceflowers** [comment]
^ +1 - I'm seeing these errors regardless of which beta I try to compile it on.

Also, I understand that the latest commits require beta4, but if I'm not ready to upgrade Xcode yet... what is the last commit on the swift-2.0 branch that is known to work with beta2?

**Comment by kamoljan** [comment]
@bruceflowers I think it didn't work for me in beta2.
But beta4 works.
